---
# tasks file for firewall-cmd
- name: Allow traffic to port
  become: true
  ansible.builtin.shell: |
    firewall-cmd \
    --permanent \
    --add-port={{ port }}/tcp

- name: reload firewalld
  become: true
  ansible.builtin.shell: |
    firewall-cmd \
    --reload

 